import datetime
x=datetime.datetime.now()
print(x)
print(x.year)
print(x.strftime('%A'))
print(x.strftime('%a'))
print(x.strftime('%w'))
print(x.strftime('%d'))
print(x.strftime('%b'))
print(x.strftime('%B'))
print(x.strftime('%m'))
print(x.strftime('%y'))
print(x.strftime('%Y'))

y=datetime.datetime(2007,6,25)
print(y)